import AuthPage from '@/components/templates/AuthPage/AuthPage'
import Head from 'next/head'

function Auth() {
  return (
    <>
      <Head>
        <title>Online shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/svg" sizes="32x32" href="/img/logo.svg" />
      </Head>
      <AuthPage />
    </>
  )
}

export default Auth
